### PR TITLE
Fix “cannot decode” error & improve performance

### LINKED ISSUE #202: Failed to generate frame: Cannot Decode
macOS v.11.0 Beta (20A5364e)
Gifski v.2.9.0 (39)

**Screenshot:**
Bildschirmfoto 2020-09-10 um 16 26 45

**Video recording:**
[Bildschirmaufnahme 2020-09-10 um 16.18.34.zip](https://github.com/sindresorhus/Gifski/files/5202315/Bildschirmaufnahme.2020-09-10.um.16.18.34.zip)

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #202
Related #220

### CODE REVIEW

File: Gifski/Utilities.swift [hunk 1]
```diff
@@ -374,11 +378,30 @@ extension AVAssetImageGenerator {
...
 					}
 
-					// macOS 11 started throwing “decode failed” error for some frames in screen recordings. As a workaround, we ignore these. We throw an error if more than 50% of the frames could not be decoded.
+					// macOS 11 (still an issue in macOS 11.1) started throwing “decode failed” error for some frames in screen recordings. As a workaround, we ignore these. We throw an error if more than 50% of the frames could not be decoded.
 					if error.code == .decodeFailed {
-						decodeFailureFrameCount += 1
-						totalCount -= 1
-						Crashlytics.recordNonFatalError(error: error, userInfo: ["requestedTime": requestedTime.seconds])
+						var newActualTime = CMTime.zero
+						if let image = try? self.copyCGImage(at: requestedTime, actualTime: &newActualTime) {
```
Comment (sindresorhus) [inline Gifski/Utilities.swift:384]: This seems to funnily succeed even when `generateCGImagesAsynchronously` failed at the same requested time 🤷🏻‍♂️

File: Gifski/Gifski.swift [hunk 2]
```diff
@@ -178,14 +178,29 @@ final class Gifski {
 
 			let generator = AVAssetImageGenerator(asset: asset)
 			generator.appliesPreferredTrackTransform = true
-			generator.requestedTimeToleranceBefore = .zero
-			generator.requestedTimeToleranceAfter = .zero
+
+			// `.zero` tolerance is much slower and fails a lot on macOS 11. (macOS 11.1)
+			if #available(macOS 11, *) {
+				generator.requestedTimeToleranceBefore = CMTime(seconds: 0.1, preferredTimescale: .video)
```
Comment (sindresorhus) [inline Gifski/Gifski.swift:184]: @kornelski Do you think it's safe to do 0.1 threshold here? Maybe it should be based on the requested FPS, but not exactly sure what heuristics to use.

Comment (kornelski) [reply Gifski/Gifski.swift:184]: that seems risky above 10fps. I'm worried that decoder could take advantage of it to snap to keyframes, so you'd have stutter around them.

I'd use `0.5/fps`, so that it's at worst half of delay in either direction.

Comment (sindresorhus) [reply Gifski/Gifski.swift]: > I'd use 0.5/fps, so that it's at worst half of frame time in either direction.

👍
