### PR TITLE
Handle video track duration being shorter than total duration

### LINKED ISSUE #119: Error: "Error.generateFrameFailed"
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gifski-app/issues/119)

This is not a crash as we handle it, but it's presented to the user and still annoying. This is a very common error that we also had with earlier versions. 133 users have been affected by this in total. 😔

Error:

```
Gifski.Error.generateFrameFailed(Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x60c00024f3f0 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}})
```

Stacktrace:

```
# Version: 2.0.0 (18)
# OS Version: 10.13.6 (17G8030)
# Device: MacBook Pro 15", Late 2011

#0. Thread
0  Gifski                         0x10fe745ab CLSUserLoggingRecordError
1  Gifski                         0x10fe58c2f -[Crashlytics recordError:withAdditionalUserInfo:]
2  Gifski                         0x10fd80ed7 @objc AppDelegate.application(_:willPresentError:) (<compiler-generated>)
3  AppKit                         0x7fff51ce7cc3 (Missing)
4  AppKit                         0x7fff52408b5d (Missing)
5  Gifski                         0x10fd85400 closure #1 in closure #1 in ConversionViewController.start(conversion:) + 1930 (util.swift:1930)
6  Gifski                         0x10fd863f7 partial apply for closure #1 in closure #1 in ConversionViewController.start(conversion:) (<compiler-generated>)
7  Gifski                         0x10fd5fa26 closure #1 in closure #1 in static Gifski.run(_:completionHandler:) + 65 (Gifski.swift:65)
8  Gifski                         0x10fd62712 partial apply for closure #1 in closure #1 in static Gifski.run(_:completionHandler:) (<compiler-generated>)
```

Relevant lines:

https://github.com/sindresorhus/Gifski/blob/7285f880644fb83b33eee64ddccbd634535ab221/Gifski/Gifski.swift#L194-L196

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gifski-app/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### LINKED ISSUE #164: Crashes when almost complete
So here is the video I'm trying to convert.  The video was taken with a Samsung phone running Android 4.4,; I have no idea if it matters? 
Action taken was reduce to 25%, lowered the quality, FPS was 15.  The conversion stopped at 96% displayed.

My first video that failed was to large to email , so, I have made a shorter video that also failed with the same error message, for your reference the filename is Gifski.mp4: [Gifski.mp4.zip](https://github.com/sindresorhus/Gifski/files/3909493/Gifski.mp4.zip)

---
Gifski 2.3.0 (26) - com.sindresorhus.Gifski
macOS 10.13.6
iMac10,1

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #119
Fixes #164

Someone finally submitted a video that reproduces the issue and I discovered why it's happening. Apparently, a video file can contain a video track that is shorter than the total file duration. We generated frame time points for the whole asset, even outside the video track. That's why `generateCGImagesAsynchronously` errored. We tried to get a frame from the video when there were none.

### CODE REVIEW

File: Gifski/VideoValidator.swift [hunk 1]
```diff
@@ -93,6 +96,25 @@ struct VideoValidator {
 			return .failure
 		}
 
+		// If the video track duration is shorter than the total asset duration, we extract the video track into a new asset to prevent problems later on.
+		guard firstVideoTrack.isFullDuration else {
```
Comment (sunshinejr) [inline Gifski/VideoValidator.swift]: do we still need to do this after you changed the code to base on the track instead of the asset?

**Comment by sunshinejr** [comment]
Ah this is a very good find! I'm wondering - can we actually create a video with multiple video tracks?

File: Gifski/VideoValidator.swift (hunk 1 above)
Comment (sindresorhus) [reply Gifski/VideoValidator.swift]: Yes, because the part of the video where there's no video track will still show in the trimmer view if not, which might confuse users, and also if the user trims it to only that part, then the conversion will start, but nothing will happen as there's nothing to convert.

Comment (sindresorhus) [reply Gifski/VideoValidator.swift]: I've expanded the comment about it: https://github.com/sindresorhus/Gifski/pull/165/commits/ebe1e7e58c01127ddb46467d1b6a381f0194ef11

**Comment by sindresorhus** [comment]
> can we actually create a video with multiple video tracks?

Yes, it's technically [supported by MP4](https://video.stackexchange.com/a/20937/1114), but not very common, and most apps don't handle it, and we definitely shouldn't care for Gifski.

**Comment by sunshinejr** [comment]
@sindresorhus ah makes sense 👍
